import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://murmur.denvermilleriii.com"),
  title: "Murmur — Stop Typing. Start Speaking.",
  description:
    "Native macOS dictation that lives in your menubar. Hold a key, say what you mean, let go. 100% local -- no cloud, no account, no tracking. Free download.",
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Murmur — Stop Typing. Start Speaking.",
    description:
      "Native macOS dictation that lives in your menubar. 100% local, no cloud, no account. Free download for Apple Silicon Macs.",
    type: "website",
    siteName: "Murmur",
    url: "/",
    // og:image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "Murmur — Stop Typing. Start Speaking.",
    description:
      "Native macOS dictation. 100% local, no cloud, no account. Free.",
  },
  keywords: [
    "dictation",
    "macOS",
    "speech to text",
    "voice typing",
    "whisper",
    "local",
    "privacy",
    "menubar app",
    "Apple Silicon",
  ],
  authors: [{ name: "Denver Miller" }],
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: "#0d0d0d",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`}>
      <body className="min-h-screen bg-[#0d0d0d] text-white font-sans">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
